apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
  annotations:
    platform.example.com/environment: prod
    platform.example.com/managed-by: root-app
spec:
  project: default

  source:
    repoURL: https://github.com/prasanakorumilli/cloud-native-ops-platform.git
    targetRevision: main
    path: charts/guestbook
    helm:
      releaseName: guestbook-prod
      valueFiles:
        - ../../environments/prod/guestbook-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true