apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/prasanakorumilli/cloud-native-ops-platform.git
    targetRevision: main
    path: charts/guestbook
    helm:
      releaseName: guestbook

  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook

syncPolicy:
  automated:
    prune: true
    selfHeal: true
