apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    app.kubernetes.io/name: guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook-ui
    spec:
      containers:
        - name: guestbook-ui
          image: gcr.io/google-samples/gb-frontend:v5
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
